const ERROR_CODE = 400;
const NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const ERROR_AUTH = 401;
const ERROR_LOCK = 423;

module.exports = {
  ERROR_CODE,
  NOT_FOUND,
  ERROR_DEFAULT,
  ERROR_AUTH,
  ERROR_LOCK,
};
